### ISSUE TITLE
Integration with dm?

### ISSUE THREAD

**Issue by krlmlr** [bergant/datamodelr#14]
@TSchiefer and myself have implemented a package that makes good use of {datamodelr}. It provides a class that stores a set of tables together with their relations and offers operations on these objects. What would be a good mode of collaboration?

https://github.com/krlmlr/dm

**Comment by bergant** [comment]
Great! This really looks like a useful R package! 
What kind of collaboration did you have in mind? I hope I will find some time to contribute, but currently I can't promise ultra short response time.

**Comment by krlmlr** [comment]
Thanks for the heads-up!

Currently the `dm` class holds an instance of `data_model`. This allowed speedy development in the beginning (because we got the data structure and the drawing for free), but we're starting to see limitations:

- ~~Compound keys aren't currently supported (krlmlr/dm#3)~~
- We'd like to support weaker relationships (krlmlr/dm#4), perhaps drawn differently
- Updates are tedious, the `$columns` and `$tables` members are redundant
- The `references` member can be `NULL`, this introduces corner cases in our code

In `dm`, tables and columns are handled by data frames or their database equivalents (lazy tables). We only need a storage for the references, ideally one that allows for compound keys. It looks like we'll refactor our internal data structure very soon to create `data_model` objects on the fly as needed. This will give us the flexibility needed for further enhancements.

Long term, we should decide if we want one or two packages. {datamodelr} is MIT, so is {dm}. For the case of two packages, a clean interface would be helpful: e.g., {datamodelr} could take care of the data structure, the API to define the referential relationships or learn them from the data, and drawing; {dm} would add handling of table data and operations on these objects. A clean interface would also help in the case of a merger.

**Comment by krlmlr** [comment]
Looks like the lack of support for compound keys is a limitation of {dm}.

**Comment by krlmlr** [comment]
As of krlmlr/dm#54, we only use the datamodelr storage format for drawing the diagram and for learning from the database.

Are you planning to submit the package to CRAN? The package still has features that dm isn't likely to support:

- column attributes
- model without data
- YAML definition

If not, we're happy to inherit your drawing code and copy it to dm, of course with attribution.

May I add you as a contributor to dm, for the code that learns from the database?

**Comment by bergant** [comment]
Please use whatever you need. I am sorry that I can't be involved more actively at this moment.

**Comment by krlmlr** [comment]
Thanks for your quick reply. I'll add you to dm's `DESCRIPTION` if you don't mind -- will send a PR.
