### ISSUE TITLE
png output?

### ISSUE THREAD

**Issue by dalloliogm** [bergant/datamodelr#2]
Thank for implementing datamodelr, it is one of the most useful libraries for data exploration.

Would it be possible to implement an option to produce png output directly, instead of html?

I think this could be implemented by calling DiagrammeR::export_graph(graph, file_type="PNG", file_name="mypng") instead of render_graph of its equivalent.

Thanks in advance and let me know if I can be of help.

**Comment by bergant** [comment]
Implemented now in new version: function `dm_export_graph`. 

Usage:

    graph <- dm_create_graph(dm)
    dm_export_graph(graph, file_name = "test", file_type = "png")

or specify type by file extension

    dm_export_graph(graph, file_name = "test.png")

**Comment by dalloliogm** [comment]
Amazing, thank you for the quick response!

**Comment by dalloliogm** [comment]
I still haven't actually managed to make it work, due to librsvg's dependency from DiagrammeR. However I'll let you know if I manage to do it, and if it works correctly.

**Comment by bergant** [comment]
Thank you for trying. It works fine on my environment, but there are some additional packages required (V8 and rsvg).
