### ISSUE TITLE
Shiny Download SVG fails

### ISSUE THREAD

**Issue by aruncps** [bergant/datamodelr#6]
When I run 
`shiny::runApp(system.file("shiny", package = "datamodelr"))`

and click **"Download SVG"** it gives the following error 
`ERROR:  'exportSVG' is not an exported object from 'namespace:DiagrammeR'`

**Comment by bergant** [comment]
Thank you for reporting this. Fixed and added a png download. Note that you need to install rsvg package (https://cran.r-project.org/package=rsvg)  for this conversion to work.

**Comment by aruncps** [comment]
It works!!! Thanks.
